### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by MostafaYA** [nf-core/bactmap#49]
Hi, 
Thanks for devloping this nice SNP pipeline, . 
I have used `bactmap` on ~200 samples using conda .  `bactmap` crashed  however every time with an error related to the memory load on the system. I used with the following setting in the command line `--max_memory 1.GB --max_cpus`  but didn't help. 

This was my full command
` nextflow run nf-core/bactmap --input samplesSheet_01Feb2022_160557.tsv --reference <ref> -profile conda --trim --outdir results_bactmap -resume --raxmlng --genome_size 1.9m --max_memory 1.GB --max_cpus 2`
I am working on a Centos machine with 1008G ram and 112 cpus. 

I appreciate your help. Thank you,

**Comment by antunderwood** [comment]
Hi @MostafaYA 

I think the problem maybe one of the processes is causing a memory problem.

Can I suggest a couple of things
1. Try reducing the number of parallel tasks to 50 using `-qs 50` in the command line
2. Post the full error here to help diagnose the problem

Thanks.

**Comment by MostafaYA** [comment]
Hi, 
thanks for your reply. Adding the flag `-qs 50` have not really solved the issue. Please find the log info here - the file STDOUT!
[files.tar.gz](https://github.com/nf-core/bactmap/files/7987160/files.tar.gz)

**Comment by antunderwood** [comment]
Hi

Are there other users running things on the server? I wonder if the memory is being consumed by other processes. As you say it looks like there is not enough memory.
Can you diagnose this by installing htop and looking at the available memory when Nextflow is running

![image](https://user-images.githubusercontent.com/423/152201051-c7ab0bdf-a607-4832-a4ca-5e4e8adc03a9.png)

**Comment by MostafaYA** [comment]
Hi, this is how it looks like on the server before the error 
![image](https://user-images.githubusercontent.com/25580655/152202545-ac048968-63f2-473a-b3f5-ba983075b9e7.png)

**Comment by MostafaYA** [comment]
only me is the current user

**Comment by antunderwood** [comment]
Looking at this I think you have too little swap for the amount of memory you have on your machine

You need at least 32Gb - see https://askubuntu.com/questions/594054/how-much-swap-should-i-take-for-1gb-to-8tb-of-ram-on-14-04-or-higher

**Comment by MostafaYA** [comment]
Thank you very much - this will have to be solved by our IT then. 

N.B. the label "bug" was unintentionally added to this thread and I have no clue how to remove it.

**Comment by andersgs** [comment]
Closing as seems resolved. Please re-open if needed.
